export const SELECT_VIDEO = 'SELECT_VIDEO';
export const FETCH_NEW_VIDEOS = 'FETCH_NEW_VIDEOS';
export const FETCH_HOT_VIDEOS = 'FETCH_HOT_VIDEOS';
export const FETCH_FIVESEVEN_VIDEOS = 'FETCH_FIVESEVEN_VIDEOS';
export const FETCH_SEVENTEN_VIDEOS = 'FETCH_SEVENTEN_VIDEOS';
export const FETCH_TENFIFTEEN_VIDEOS = 'FETCH_TENFIFTEEN_VIDEOS';
export const FETCH_HALFHOUR_VIDEOS = 'FETCH_HALFHOUR_VIDEOS';